friendly_name = "Sleep"
py_script = "sleep.py"
presentmon_enabled = false
executable = ""
category = "utility"
save_run = false
[[args]]
name = "seconds"
type = "input"
tooltip = "Time to sleep in seconds"
default = "900"
