friendly_name = "Assassins Creed Black Flag Resynced"
py_script = "assassins_creed_black_flag_resynced.py"
executable = "ACBlackFlag.exe"
presentmon_enabled = true
presentmon_ignore_exit = true
category = "game"
ocr = true
