friendly_name = "Forza Motorsport"
py_script = "forza_motorsport.py"
executable = "forza_steamworks_release_final.exe"
presentmon_enabled = true
presentmon_ignore_exit = true
category = "game"
ocr = true
