friendly_name = "F1 24 Stress"
py_script = "f1_stress.py"
executable = "F1_24.exe"
presentmon_enabled = true
presentmon_ignore_exit = true
ocr_enabled = true
category = "stress"
ocr = true

[[args]]
name = "hardware_settings"
type = "select"
tooltip = "Select the hardware settings XML to copy"
default = "games-1080-ultra.xml"
values = [
  "games-1080-ultra.xml",
  "games-2160-ultra-rt.xml"
]

[[args]]
name = "duration_seconds"
type = "input"
tooltip = "Stress duration in seconds"
default = "900"
