friendly_name = "PugetBench"
py_script = "pugetbench.py"
executable = "PugetBench for Creators.exe"
presentmon_enabled = false
category = "non_game"
ocr = false

[[args]]
name = "app"
type = "select"
tooltip = "Select which test to run"
values = ["premierepro", "photoshop", "aftereffects", "lightroom", "resolve", "unreal"]

[[args]]
name = "benchmark_version"
type = "input"
tooltip = "Version of benchmark to run"

[[args]]
name = "preset"
type = "select"
tooltip = "Select which benchmark preset to run"
values = ["Standard", "Extended"]
