friendly_name = "Godot Compile"
py_script = "godot_compile.py"
executable = "HandBrakeCLI.exe"
presentmon_enabled = false
category = "non_game"
ocr = false

[[args]]
name = "architecture"
type = "select"
tooltip = "Target architecture to build Godot for (cross-compiles if it differs from this machine)"
values = ["x86_64", "arm64"]
