name: Linting

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: streetsidesoftware/cspell-action@v8
        with:
          files: "**/*.md"
          incremental_files_only: false

  exec_pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check --output-format=github"
