name: Linting

on:
  pull_request:
    branches: [ "main" ]

jobs:
  # For more info see:
  # https://github.com/streetsidesoftware/cspell-action
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v3
  exec_pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git diff --name-only -r HEAD^1 HEAD -- '*.py')